# Generated by Django 3.1.7 on 2021-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210404_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('T', 'Teacher'), ('A', 'Administration'), ('S', 'Student')], default='S', max_length=1),
        ),
    ]
