# Generated by Django 3.1.7 on 2021-05-12 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clasroom', '0003_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='clasroom.classroom'),
        ),
        migrations.AlterField(
            model_name='enrolledclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
