# Generated by Django 3.1.7 on 2021-05-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clasroom', '0004_auto_20210512_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='module-notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasroom.modules')),
            ],
        ),
    ]
